mysite/config/urls.py
from django.contrib import admin
from django.urls import path ,include
from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
]

mysite/pybo/urls.py
from django.urls import path
from . import views

app_name = 'pybo'

urlpatterns = [
    # localhost:8000/pybo 주소의 루트를 의미함
    path('', views.index, name = "index"),
    #게시글 제목의 a 태그 href 속성에 해당하는 동적 URL 매핑
    path("<int:question_id>",views.detail, name = "detail"), # name 옵션으로 별칭 지정이 가능하다.
    #답변 등록에 대한 URL 매핑
    path("answer/create/<int:question_id>",views.answer_create, name = "answer_create"), # name 옵션으로 별칭 지정이 가능하다.
]

mysite/pybo/models.py
from django.db import models
#스프링의 @Entity를 사용하여 회원가입 Class 생성했던 것과 유사함
# @Entity = DB에 저장되는 객체로 인식하는 어노테이션

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200) #문자열 길이를 제한할 때 사용
    content = models.TextField() # 문자열 제한이 없는 데이터 타입
    create_date = models.DateTimeField() # 날짜와 시간

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.content

mysite/pybo/views.py
from django.shortcuts import render ,get_object_or_404, redirect
from django.http import HttpResponse
from.models import Question, Answer
from django.utils import timezone
# Create your views here.

def index(request):
    question_list = Question.objects.order_by('-create_date') # 최신순 정렬하기 위해 내림차순 - 붙임
    context = {"question_list":question_list}
    return render(request, 'pybo/question_list.html',context)
    # Templates 경로는 c:\chang_git\mysite\templates이다.
    # 위에서 렌더링은 'pybo\question_list.html'로 지정했다 -> 'pybo/' 경로를 직접 생성하는 과정이 필요하다.
    # 그러면 'pybo/question_list.html'이 아니라 'question_list.html이 렌더링 경로로 설정되면 되는거 아니냐? 싶지만
    # 브라우저에서 접속시에 www.naver.com/blog 처럼 나오게 하기 위해서 위처럼 파일경로를 생성하여 만든다.

    # 해당 문자열을 Http방식으로 반환해주는 메소드
    #return HttpResponse("<h1>안녕하세요. Pybo 메인 페이지 입니다.</h1>")

def detail(request, question_id):
    #question = Question.objects.get(id=question_id) # 그냥 받을 때

    question = get_object_or_404(Question, pk = question_id)#에러 처리 할때
    context = {'question' : question}
    return render(request,'pybo/question_detail.html',context)

def answer_create(request, question_id):
    question = get_object_or_404(Question,pk = question_id)
    request.POST.get("content")
    # save() 랑 동일한 기능이고 create안에 들어가는 값이 만들어지는 값임
    question.answer_set.create(content = request.POST.get("content") , create_date= timezone.now())
    return redirect("pybo:detail", question_id = question_id)

mysite/templates/pybo/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.subject }}</h1>
    <div>{{ question.content }}</div>

    <hr>
    <h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    <div>
        <ul>
            {% for answer in question.answer_set.all  %}
                <li>{{ answer.content }}</li>
            {% endfor %}
        </ul>
    </div>
    <hr>

    <form action="{% url 'pybo:answer_create' question.id %}" method="post">
        {% csrf_token %} <!-- CSRF 공격을 막기 위해 명시적으로 넣어줘야 실행됨.-->
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
        <input type="submit" value = "답변등록">
    </form>
</body>
</html>

mysite/templates/pybo/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset='UTF-8'>
</head>
<body>
    {% if question_list %}
    <ul>
    {% for question in question_list %}
        <!--<li><a href="/pybo/{{ question.id}}">{{question.subject}}</a></li> 원래 코드-->
        <li><a href = "{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li><!-- 별칭 수정한 코드-->
    {% endfor %}
    </ul>
    {% else %}
    <p>질문이 없습니다.</p>
    {% endif %}



</body>
</html>